version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.12.1  #镜像
    container_name: elk_elasticsearch  #定义容器名称
    restart: always  #开机启动，失败也会一直重启
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ../volume/es/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200

    networks:
      default:
        ipv4_address: "172.21.0.13"

networks:
  default:
    external:
      name: mynetwork

