version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ../etc/mysql/my.cnf:/etc/my.cnf
#      - ../etc/mysql/init/:/docker-entrypoint-initdb.d/
      - ../volume/mysql:/tmp/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3308:3306
    networks:
      default:
        ipv4_address: "172.21.0.3"

networks:
  default:
    external:
      name: mynetwork